version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ecoblocks_user
      POSTGRES_PASSWORD: ecoblocks_password
      POSTGRES_DB: ecoblocks_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ecoblock-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - ecoblock-network

  ecoblock-api:
    build: ./ecoblock-api
    depends_on:
      - db
      - mongodb
      - ecoblock-blockchain
    environment:
      DATABASE_URL: postgres://ecoblocks_user:ecoblocks_password@db:5432/ecoblocks_db
      MONGO_URL: mongodb://mongodb:27017/Ecoblocks
      SERVER_ADDRESS: "0.0.0.0:8000"
      BLOCKCHAIN_URL: http://ecoblock-blockchain:9000
    ports:
      - "8000:8000"
    networks:
      - ecoblock-network

  ecoblock-blockchain:
    build: ./ecoblock-blockchain
    environment:
      SERVER_ADDRESS: "0.0.0.0:9000"
    ports:
      - "9000:9000"
    networks:
      - ecoblock-network

  ecoblock-webapp:
    build: ./ecoblock-webapp
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BACKEND_URL=http://ecoblock-api:8000
      - REACT_APP_BLOCKCHAIN_URL=http://ecoblock-blockchain:9000
    networks:
      - ecoblock-network

  # ecoblock-cms:
  #   build: ./ecoblock-cms
  #   ports:
  #     - "3001:3001"
  #   environment:
  #     - REACT_APP_BACKEND_URL=http://ecoblock-api:8000
  #   networks:
  #     - ecoblock-network

volumes:
  db_data:
  mongodb_data:

networks:
  ecoblock-network:
