# Use the official Rust image as a base
FROM rust:latest

# Set the working directory inside the container
WORKDIR /usr/src/ecoblock-blockchain

# Copy the Cargo.toml and Cargo.lock files
COPY Cargo.toml Cargo.lock ./

# Copy the source code
COPY src ./src

# Copy the .env file
COPY .env .env

# Install required tools
RUN apt-get update && apt-get install -y \
    libssl-dev pkg-config

# Build the application in release mode
RUN cargo build --release

# Set environment variables from .env file
ENV $(cat .env | xargs)

# Expose the port the application will run on
EXPOSE 9000

# Run the application
CMD ["./target/release/ecoblock-blockchain"]
