FROM rust:latest

WORKDIR /usr/src/ecoblock-blockchain

COPY Cargo.toml Cargo.lock ./

COPY src ./src

COPY .env .env

RUN apt-get update && apt-get install -y \
    libssl-dev pkg-config

RUN cargo build --release

ENV $(cat .env | xargs)

EXPOSE 9000

CMD ["./target/release/ecoblock-blockchain"]
